# Generated by Django 6.0.2 on 2026-02-21 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Kontrak MBG', max_length=160)),
                ('start_date', models.DateField()),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('price_per_portion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_portions_per_day', models.PositiveIntegerField(default=1000)),
                ('target_margin_pct', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('portions', models.PositiveIntegerField()),
                ('cost_material', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost_labor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost_overhead', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.contract')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'unique_together': {('contract', 'date')},
            },
        ),
    ]
