# Generated by Django 6.0.2 on 2026-02-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='credit_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Tunai'), ('CREDIT', 'Kredit')], default='CASH', max_length=10),
        ),
    ]
